### ISSUE TITLE
Permission denied: '/usr/local/lib/python3.6/dist-packages/funmotd/config.json'

### ISSUE THREAD

**Issue by veerendra2** [veerendra2/funmotd#1]
```
veeru@carb0n:~$ funmotd -e game_of_thrones 100
Traceback (most recent call last):
  File "/usr/local/bin/funmotd", line 11, in <module>
    load_entry_point('funmotd==0.1', 'console_scripts', 'funmotd')()
  File "/usr/local/lib/python3.6/dist-packages/funmotd/__init__.py", line 101, in main
    modify_config(None, results.modify)
  File "/usr/local/lib/python3.6/dist-packages/funmotd/__init__.py", line 63, in modify_config
    write_config(config)
  File "/usr/local/lib/python3.6/dist-packages/funmotd/__init__.py", line 31, in write_config
    with open(config_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/funmotd/config.json'
```

**Comment by veerendra2** [comment]
Quick workaround. use `sudo`
```
$ sudo funmotd -e game_of_thrones 100
```

**Comment by veerendra2** [comment]
Fixed. https://github.com/veerendra2/funmotd/commit/a3a760e90db2c1bca061dab90dd1428416d54bb8
